from django.conf.urls import url
from .views import (
    CreateEventView,
    UpcomingEventsView,
    OngoingEventsView,
    FinishedEventsView,
    EventProfileView,
    CreatorEventProfileView,
    SendEntryView,
    AllEntriesView,
    ApproveEntryView,
    RejectEntryView
)

urlpatterns = [
    url(r'^createevent/$', CreateEventView.as_view(), name='createevent'),
    url(r'^upcomingevents/$',
        UpcomingEventsView.as_view(),
        name='upcomingevents'),
    url(r'^ongoingevents/$',
        OngoingEventsView.as_view(),
        name='ongoingevents'),
    url(r'^finishedevents/$',
        FinishedEventsView.as_view(),
        name='finishedevents'),
    url(r'^eventprofile/$',
        EventProfileView.as_view(),
        name='eventprofile'),
    url(r'^creatoreventprofile/$',
        CreatorEventProfileView.as_view(),
        name='creatoreventprofile'),
    url(r'^sendentry/$',
        SendEntryView.as_view(),
        name='sendentry'),
    url(r'^allentries/$',
        AllEntriesView.as_view(),
        name='allentries'),
    url(r'^approveentry/$',
        ApproveEntryView.as_view(),
        name='approveentry'),
    url(r'^rejectentry/$',
        RejectEntryView.as_view(),
        name='rejectentry'),
]
