# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-04 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_image',
            field=models.ImageField(default='event_image/default_profpic.png', upload_to='event_image/'),
        ),
    ]
