# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-07 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='entry_status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Pending'), (1, 'Rejected'), (2, 'Accepted')], default=0),
        ),
    ]
