# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-15 10:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='event_id',
            new_name='event',
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='user_id',
            new_name='user',
        ),
    ]
