# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-15 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20180315_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='prize',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
