# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-05 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_auto_20180404_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_image',
            field=models.ImageField(default='event_image/default.png', upload_to='event_image/'),
        ),
    ]
