# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-12 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_auto_20180405_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date_ended',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='voting_status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Open'), (1, 'Closed')], default=0),
        ),
    ]
