# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-12 08:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_auto_20180412_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Upcoming'), (1, 'Ongoing'), (2, 'Finished'), (3, 'Canceled')], default=0),
        ),
    ]
