# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-07 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='bio',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
