# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-25 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_auto_20180325_0732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='user_video',
            field=models.FileField(blank=True, upload_to='uploads/'),
        ),
    ]
