# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-25 07:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_auto_20180325_0736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='profile_image/'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user_video',
            field=models.FileField(blank=True, upload_to='profile_video/'),
        ),
    ]
