# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-26 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_auto_20180325_0737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='profile_pic',
            field=models.ImageField(default='profile_image/default.png', upload_to='profile_image/'),
        ),
    ]
