# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-26 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0006_auto_20180326_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='user_video',
            field=models.FileField(blank=True, default='profile_video/default', upload_to='profile_video/'),
        ),
    ]
