# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-28 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0009_userinfo_video_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='video_thumbnail',
            field=models.ImageField(blank=True, default='video_thumbnail/default.png', upload_to='video_thumbnail/'),
        ),
    ]
