# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-28 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0016_auto_20180328_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='profile_pic',
            field=models.ImageField(default='profile_image/default_profpic.png', upload_to='profile_image/'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user_video',
            field=models.FileField(default='video_thumbnail/default_video.png', upload_to='profile_video/'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='video_thumbnail',
            field=models.ImageField(default='video_thumbnail/default_thumbail.png', upload_to='video_thumbnail/'),
        ),
    ]
