# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-28 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0017_auto_20180328_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='user_video',
            field=models.FileField(default='profile/default_video.mp4', upload_to='profile_video/'),
        ),
    ]
