# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-28 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0018_auto_20180328_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='bio',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user_video',
            field=models.FileField(default='profile_video/default_video.mp4', upload_to='profile_video/'),
        ),
    ]
