# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-10 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0023_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='is_active',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
