# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-07 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestream', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='archive_id',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='episode',
            name='session_id',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
