# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-07 19:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('livestream', '0002_auto_20180408_0244'),
    ]

    operations = [
        migrations.CreateModel(
            name='Viewer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_voted', models.PositiveSmallIntegerField(choices=[(0, 'has_not_voted'), (1, 'has_voted')], default=0)),
            ],
        ),
        migrations.AddField(
            model_name='episode',
            name='views',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='viewer',
            name='episode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewers', to='livestream.Episode'),
        ),
        migrations.AddField(
            model_name='viewer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewers', to=settings.AUTH_USER_MODEL),
        ),
    ]
