# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-08 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestream', '0005_auto_20180408_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='archive_id',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='session_id',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
